# Generated by Django 5.2.9 on 2025-12-28 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text='URL friendly name (e.g. pneumonia-detection)', unique=True)),
                ('summary', models.CharField(help_text='Short tagline for the card view', max_length=255)),
                ('description', models.TextField(help_text='Full case study. Markdown supported.')),
                ('cover_image', models.ImageField(upload_to='projects/')),
                ('technologies', models.CharField(help_text='Comma separated: PyTorch, Docker, Azure', max_length=255)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on Homepage Hero?')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('github', 'GitHub Repo'), ('kaggle', 'Kaggle Notebook'), ('swagger', 'Swagger API'), ('demo', 'Live Demo'), ('paper', 'Research Paper')], max_length=20)),
                ('url', models.URLField()),
                ('label', models.CharField(blank=True, help_text='Override button text (optional)', max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Accuracy, F1-Score, Latency', max_length=50)),
                ('value', models.CharField(help_text='e.g. 91%, 20ms, 0.85', max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='projects.project')),
            ],
        ),
    ]
