# Generated by Django 5.2.9 on 2026-01-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('language', 'Programming Language'), ('framework', 'Framework/Library'), ('tool', 'Tool/Platform'), ('concept', 'Concept')], max_length=20)),
                ('icon', models.ImageField(blank=True, help_text='Small SVG or PNG logo', null=True, upload_to='skills/')),
                ('is_featured', models.BooleanField(default=False, help_text="Show in the 'About Me' tech stack matrix?")),
            ],
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-date_issued']},
        ),
        migrations.AlterField(
            model_name='certificate',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='related_skills',
            field=models.ManyToManyField(blank=True, to='resume.skill'),
        ),
        migrations.AddField(
            model_name='experience',
            name='related_skills',
            field=models.ManyToManyField(blank=True, to='resume.skill'),
        ),
    ]
